import { Product, SubscriptionInterval } from "./types";

export const SUBSCRIPTION_INTERVALS: SubscriptionInterval[] = [
  { label: "Every 4 weeks", interval: "week", intervalCount: 4, discountPercent: 15 },
  { label: "Every 8 weeks", interval: "week", intervalCount: 8, discountPercent: 12 },
  { label: "Every 12 weeks", interval: "week", intervalCount: 12, discountPercent: 10 },
];

export const PRODUCTS: Product[] = [
  {
    id: "prod_turmeric_gold",
    slug: "turmeric-gold-root-powder",
    name: "Turmeric Gold Root Powder",
    category: "Superfood Powders",
    tagline: "High-curcumin turmeric from Erode, India",
    description:
      "Hand-harvested turmeric root, sun-dried and stone-ground in small batches to preserve its curcumin content. Earthy, warm, and easy to stir into golden milk, curries, or a morning smoothie.",
    origin: "Erode, Tamil Nadu, India",
    benefits: ["Supports joint comfort", "Antioxidant-rich", "Soothes digestion"],
    ingredients: ["100% organic turmeric root (Curcuma longa)"],
    priceCents: 2400,
    sizeLabel: "8 oz pouch",
    accent: "from-fuchsia-500 to-rose-700",
    badge: "Bestseller",
  },
  {
    id: "prod_ashwagandha",
    slug: "himalayan-ashwagandha-root",
    name: "Himalayan Ashwagandha Root",
    category: "Adaptogens",
    tagline: "Traditional KSM-grade adaptogen root",
    description:
      "Grown at altitude in the foothills of the Himalayas, this ashwagandha root is dried slowly and milled fine. A daily ritual for people who want calmer days and deeper sleep.",
    origin: "Himachal Pradesh, India",
    benefits: ["Eases everyday stress", "Supports restful sleep", "Balances energy"],
    ingredients: ["Organic ashwagandha root (Withania somnifera)"],
    priceCents: 2800,
    sizeLabel: "60 capsules",
    accent: "from-purple-500 to-violet-800",
  },
  {
    id: "prod_matcha",
    slug: "ceremonial-matcha",
    name: "Ceremonial Grade Matcha",
    category: "Herbal Teas",
    tagline: "Shade-grown matcha from Uji, Japan",
    description:
      "Stone-milled matcha from first-harvest tea leaves shade-grown for 30 days before picking. Vibrant green, naturally sweet, and smooth — no bitterness, no fillers.",
    origin: "Uji, Kyoto Prefecture, Japan",
    benefits: ["Gentle, sustained energy", "Rich in catechins", "Supports focus"],
    ingredients: ["100% ceremonial grade green tea (Camellia sinensis)"],
    priceCents: 3200,
    sizeLabel: "30g tin",
    accent: "from-emerald-500 to-green-700",
    badge: "New",
  },
  {
    id: "prod_elderberry",
    slug: "wildcrafted-elderberry-syrup",
    name: "Wildcrafted Elderberry Syrup",
    category: "Immune Support",
    tagline: "Old-world elderberries, slow-simmered",
    description:
      "Foraged black elderberries simmered with raw honey, clove, and ginger using a generations-old recipe. A pantry staple for cold season, straight off the spoon.",
    origin: "Carpathian foothills, Eastern Europe",
    benefits: ["Immune support", "Rich in anthocyanins", "Soothing for the throat"],
    ingredients: ["Wildcrafted elderberries", "Raw honey", "Ginger root", "Clove"],
    priceCents: 2600,
    sizeLabel: "8 fl oz bottle",
    accent: "from-rose-500 to-fuchsia-800",
  },
  {
    id: "prod_moringa",
    slug: "sundried-moringa-leaf",
    name: "Sun-Dried Moringa Leaf",
    category: "Superfood Powders",
    tagline: "Nutrient-dense moringa from smallholder farms",
    description:
      "Moringa leaves shade-dried within hours of harvest to lock in chlorophyll and micronutrients. A gentle, grassy addition to green juice or soups.",
    origin: "Iringa Region, Tanzania",
    benefits: ["Dense in vitamins & minerals", "Supports energy", "Gentle daily greens"],
    ingredients: ["100% organic moringa leaf (Moringa oleifera)"],
    priceCents: 2200,
    sizeLabel: "6 oz pouch",
    accent: "from-lime-500 to-emerald-700",
  },
  {
    id: "prod_reishi",
    slug: "aged-reishi-mushroom-extract",
    name: "Aged Reishi Mushroom Extract",
    category: "Adaptogens",
    tagline: "Dual-extracted reishi, grown on oak logs",
    description:
      "Reishi mushrooms grown on hardwood logs for 18 months, then dual-extracted in water and alcohol to draw out beta-glucans and triterpenes. Woody, calming, and grounding before bed.",
    origin: "Fujian Province, China",
    benefits: ["Calms the nervous system", "Supports immune balance", "Evening wind-down ritual"],
    ingredients: ["Aged reishi mushroom dual extract (Ganoderma lucidum)"],
    priceCents: 3400,
    sizeLabel: "2 fl oz dropper",
    accent: "from-fuchsia-600 to-purple-900",
  },
  {
    id: "prod_chamomile",
    slug: "alpine-chamomile-flower-tea",
    name: "Alpine Chamomile Flower Tea",
    category: "Herbal Teas",
    tagline: "Whole flower chamomile, hand-picked",
    description:
      "Whole chamomile flowers hand-picked from alpine meadows and air-dried whole, so every cup carries their full honeyed aroma. Caffeine-free, any time of day.",
    origin: "Nile Delta, Egypt",
    benefits: ["Calming evening tea", "Supports digestion", "Caffeine-free"],
    ingredients: ["Whole dried chamomile flowers (Matricaria chamomilla)"],
    priceCents: 1800,
    sizeLabel: "3.5 oz loose leaf tin",
    accent: "from-pink-400 to-rose-600",
  },
  {
    id: "prod_frankincense",
    slug: "sacred-frankincense-oil",
    name: "Sacred Frankincense Oil",
    category: "Essential Oils",
    tagline: "Steam-distilled Boswellia resin",
    description:
      "Resin tapped from wild Boswellia sacra trees and steam-distilled near the harvest site to preserve its warm, resinous character. A grounding addition to any evening ritual.",
    origin: "Dhofar Region, Oman",
    benefits: ["Grounding aromatherapy", "Supports mindful breathing", "Skin-soothing"],
    ingredients: ["100% pure frankincense essential oil (Boswellia sacra)"],
    priceCents: 3800,
    sizeLabel: "15 mL bottle",
    accent: "from-orange-400 to-rose-800",
  },
  {
    id: "prod_spirulina",
    slug: "bluegreen-spirulina-powder",
    name: "Blue-Green Spirulina Powder",
    category: "Superfood Powders",
    tagline: "Lake-grown, low-temperature dried",
    description:
      "Spirulina cultivated in mineral-rich volcanic lakes and dried at low temperatures to protect its phycocyanin content. A concentrated boost for smoothies and energy bites.",
    origin: "Lake Myvatn region, Iceland",
    benefits: ["Dense plant protein", "Rich in phycocyanin", "Post-workout recovery"],
    ingredients: ["100% organic spirulina (Arthrospira platensis)"],
    priceCents: 2900,
    sizeLabel: "7 oz pouch",
    accent: "from-blue-500 to-indigo-700",
  },
  {
    id: "prod_eucalyptus",
    slug: "wild-eucalyptus-oil",
    name: "Wild Eucalyptus Oil",
    category: "Essential Oils",
    tagline: "Steam-distilled from wild groves",
    description:
      "Eucalyptus leaves harvested from wild groves and steam-distilled within a day of picking for a bright, camphorous aroma. Diffuse it, or add a drop to your shower steam.",
    origin: "New South Wales, Australia",
    benefits: ["Clears the senses", "Invigorating aromatherapy", "Refreshing in steam or diffuser"],
    ingredients: ["100% pure eucalyptus essential oil (Eucalyptus globulus)"],
    priceCents: 1900,
    sizeLabel: "15 mL bottle",
    accent: "from-sky-500 to-blue-800",
  },
  {
    id: "prod_hibiscus",
    slug: "sundried-hibiscus-tea",
    name: "Sun-Dried Hibiscus Tea",
    category: "Herbal Teas",
    tagline: "Tart, ruby-red hibiscus flowers",
    description:
      "Hibiscus petals sun-dried on woven mats until deep ruby red. Steeped hot or cold-brewed, it pours a tart, cranberry-bright cup that's naturally caffeine-free.",
    origin: "Sokoto State, Nigeria",
    benefits: ["Naturally caffeine-free", "Vitamin C-rich", "Refreshing hot or iced"],
    ingredients: ["Whole dried hibiscus flowers (Hibiscus sabdariffa)"],
    priceCents: 1700,
    sizeLabel: "4 oz loose leaf tin",
    accent: "from-rose-500 to-pink-800",
  },
  {
    id: "prod_bundle_immunity",
    slug: "immunity-ritual-bundle",
    name: "Immunity Ritual Bundle",
    category: "Wellness Bundles",
    tagline: "Elderberry syrup, ginger chips & hibiscus tea",
    description:
      "Our three most-loved immune staples in one bundle: wildcrafted elderberry syrup, sun-dried ginger root chips, and vitamin-C-rich hibiscus tea. Built for the season when your body needs a little more support.",
    origin: "Sourced from Eastern Europe, China & Nigeria",
    benefits: ["Daily immune support", "Warming & soothing", "Great as a gift set"],
    ingredients: ["Wildcrafted elderberry syrup", "Dried ginger root chips", "Sun-dried hibiscus flowers"],
    priceCents: 5400,
    sizeLabel: "3-piece bundle",
    accent: "from-rose-500 to-fuchsia-800",
    badge: "Bundle & Save",
  },
  {
    id: "prod_bundle_calm",
    slug: "calm-and-sleep-bundle",
    name: "Calm & Sleep Ritual Bundle",
    category: "Wellness Bundles",
    tagline: "Ashwagandha, reishi extract & chamomile tea",
    description:
      "A slow-down trio for the end of the day: ashwagandha root capsules, dual-extracted reishi mushroom, and whole-flower chamomile tea. Designed to be sipped, taken, and repeated as a nightly wind-down.",
    origin: "Sourced from India, China & Egypt",
    benefits: ["Supports relaxation", "Evening wind-down ritual", "Caffeine-free"],
    ingredients: ["Ashwagandha root capsules", "Reishi mushroom dual extract", "Whole chamomile flower tea"],
    priceCents: 6200,
    sizeLabel: "3-piece bundle",
    accent: "from-indigo-500 to-purple-900",
    badge: "Bundle & Save",
  },
  {
    id: "prod_bundle_starter",
    slug: "wellness-starter-bundle",
    name: "Wellness Starter Bundle",
    category: "Wellness Bundles",
    tagline: "Turmeric, moringa & ceremonial matcha",
    description:
      "The easiest way to try Love - N - Living Healthy: our high-curcumin turmeric, nutrient-dense moringa leaf, and ceremonial matcha, sized to slot into smoothies, teas, and everyday cooking.",
    origin: "Sourced from India, Tanzania & Japan",
    benefits: ["A gentle introduction to our range", "Everyday superfoods", "Great in smoothies"],
    ingredients: ["Turmeric root powder", "Moringa leaf powder", "Ceremonial matcha"],
    priceCents: 5900,
    sizeLabel: "3-piece bundle",
    accent: "from-green-400 to-emerald-700",
    badge: "Bundle & Save",
  },
  {
    id: "prod_ginger",
    slug: "dried-ginger-root-chips",
    name: "Dried Ginger Root Chips",
    category: "Immune Support",
    tagline: "Sun-dried ginger, sliced thin",
    description:
      "Young ginger rhizomes sliced thin and sun-dried until they turn slightly chewy and intensely spicy-sweet. Simmer into tea or nibble on straight from the jar.",
    origin: "Yunnan Province, China",
    benefits: ["Soothes upset stomach", "Warming immune support", "Great in tea or snacking"],
    ingredients: ["100% sun-dried ginger root (Zingiber officinale)"],
    priceCents: 1600,
    sizeLabel: "6 oz jar",
    accent: "from-orange-400 to-yellow-700",
  },
];

export const CATEGORIES = Array.from(new Set(PRODUCTS.map((p) => p.category)));

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
